url: https://emuid.github.io

# Site settings
title: EMU:ID
email: libby.murrell@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Libby Upson
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: https://twitter.com/emuid
    - title: facebook
      url: https://www.facebook.com/libby.upson
    - title: linkedin
      url: https://uk.linkedin.com/in/libby-upson-b2817415

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/emuid
  - title: facebook
    url: https://www.facebook.com/libby.upson
  - title: linkedin
    url: https://uk.linkedin.com/in/libby-upson-b2817415

# Postal address (add as many lines as necessary)
address:
  - line: 132 Missenden Acres, Hedge End
  - line: Southampton, UK, SO30 2AQ

# Build settings
markdown: kramdown
permalink: pretty